version: "3.8"
   
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  django:
    build: .
    command: "python manage.py runserver 0.0.0.0:33325"
    ports:
      - "33325:33325"
    depends_on:
      - db