version: "3.8"
   
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes: 
      - postgres_data:/var/lib/postgresql/data/
  backend:
    build: .
    environment:
      - DJANGO_DATABASE=postgres
    command: >
      sh -c "./wait-for-it.sh db:5432 &&
             python manage.py makemigrations users &&
             python manage.py migrate --database=postgres &&
             python manage.py runserver 0.0.0.0:33325"
    ports:
      - "33325:33325"
    depends_on:
      - db

  docs:
    image: squidfunk/mkdocs-material
    volumes: 
      - .:/docs
    ports:
      - "33324:8000"
  
volumes: 
  postgres_data: