version: "3.8"
services:
  
  db:
    image: postgres
    container_name: backend_db
    env_file: .env
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    volumes: 
      - /var/lib/codershq/postgres/:/var/lib/postgresql/data/

  redis:
    container_name: backend_redis
    image: "redis:alpine"
  
  web:
    build: .
    container_name: backend_django
    env_file: .env
    environment:
      - DJANGO_DATABASE=postgres
    command: >
      sh -c "./wait-for-it.sh db:5432 &&
             python manage.py makemigrations users &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:33325"
    volumes: 
      - ".:/app/backend"
    ports:
      - "33325:33325"
    depends_on:
      - db
      - redis
      - celery

  celery:
    build: .
    container_name: backend_celery
    command: celery -A chq_backend worker -l INFO
    env_file: .env
    volumes:
      - ".:/app/backend"
    depends_on:
      - db
      - redis

  docs:
    container_name: backend_mkdocs
    build: docs
    volumes: 
      - .:/docs
    ports:
      - "33324:8000"
  