version: "3.8"
   
services:
  
  db:
    image: postgres
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    volumes: 
      - /var/lib/codershq/postgres/:/var/lib/postgresql/data/
  
  backend:
    build: .
    container_name: backend_django
    environment:
      - DJANGO_DATABASE=postgres
    command: >
      sh -c "./wait-for-it.sh db:5432 &&
             python manage.py makemigrations users &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:33325"
    volumes: 
      - ".:/app/backend"
    ports:
      - "33325:33325"
    depends_on:
      - db
      - redis

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  docs:
    container_name: mkdocs
    build: docs
    volumes: 
      - .:/docs
    ports:
      - "33324:8000"
  