site_name: Coders HQ Documentation
repo_url: https://github.com/Coders-HQ/CHQ_Backend/
edit_uri: '?query=docs/'
site_description: This documentation site holds the Coders-HQ backend's information.
site_url: 'https://docs.codershq.ae'
nav:
    - Suggestions: 'suggestions.md'
    - News: "news.md"

theme:
  name: 'material'