# build mkdocs documentation  on commit

name: Build Documentation
on:
  push:
    branches:
      - master
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      # Deploy
      - uses: actions/setup-python@v2

        with:
          python-version: 3.x
      - run: |
          pip install mkdocs-material
          pip install plantuml-markdown
      - run: mv README.md docs/
      - run: mkdocs gh-deploy --force
